/* VERSION and PRECACHE are generated by offline-plugin.js. */
const PREFIX = `polaris-${encodeURIComponent(self.registration.scope)}-`;
const SHELL = `${PREFIX}${VERSION}-shell`;
const ART = `${PREFIX}${VERSION}-art`;
const scopedUrl = (path) => new URL(path, self.registration.scope).href;
const shellUrls = new Set(PRECACHE.map(scopedUrl));

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(SHELL);
      // addAll is atomic: a missing file prevents this worker from replacing the active one.
      await cache.addAll([...shellUrls].map((url) => new Request(url, { cache: 'reload' })));
    } catch (error) {
      await caches.delete(SHELL);
      throw error;
    }
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // Keep one previous shell for requests from tabs finishing their update.
    const names = (await caches.keys()).filter((name) => name.startsWith(PREFIX));
    const previous = names.filter((name) => name.endsWith('-shell') && name !== SHELL).at(-1);
    await Promise.all(names.filter((name) => name !== SHELL && name !== ART && name !== previous)
      .map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

async function respond(request) {
  const shell = await caches.open(SHELL);
  // HTML is pinned to this worker's build, never overwritten by a newer network HTML.
  if (request.mode === 'navigate') {
    return (await shell.match(scopedUrl('index.html'))) || fetch(request);
  }
  const cached = await shell.match(request);
  if (cached) return cached;
  if (new URL(request.url).pathname.includes('/assets/')) {
    for (const name of await caches.keys()) {
      if (name.startsWith(PREFIX) && name.endsWith('-shell')) {
        const previous = await (await caches.open(name)).match(request);
        if (previous) return previous;
      }
    }
  }
  const artRequest = new URL(request.url).pathname.startsWith(new URL('art/', self.registration.scope).pathname);
  const art = artRequest ? await caches.open(ART) : null;
  const illustration = await art?.match(request);
  if (illustration) return illustration;
  try {
    const response = await fetch(request);
    if (art && response.ok) {
      try {
        await art.put(request, response.clone());
        const keys = await art.keys();
        for (const key of keys.slice(0, Math.max(0, keys.length - 40))) await art.delete(key);
      } catch { /* Storage pressure must not prevent online display. */ }
    }
    return response;
  } catch {
    // A real response lets image onError fall back to the constellation drawing.
    return new Response('', { status: 503, statusText: 'Offline' });
  }
}

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin
    || !url.href.startsWith(self.registration.scope)) return;
  event.respondWith(respond(event.request));
});
